//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.20 at 01:20:02 PM IST 
//

package com.po.reservation.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="poRequestId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "poRequestId", "userId" })
@XmlRootElement(name = "AddContainerDetailsRequest", namespace = "http://www.addcontainerdetails.com/addcontainerdetails")
public class AddContainerDetailsRequest {

	@XmlElement(namespace = "http://www.addcontainerdetails.com/addcontainerdetails")
	protected int poRequestId;
	@XmlElement(namespace = "http://www.addcontainerdetails.com/addcontainerdetails")
	protected int userId;

	/**
	 * Gets the value of the poRequestId property.
	 * 
	 */
	public int getPoRequestId() {
		return poRequestId;
	}

	/**
	 * Sets the value of the poRequestId property.
	 * 
	 */
	public void setPoRequestId(int value) {
		this.poRequestId = value;
	}

	/**
	 * Gets the value of the userId property.
	 * 
	 */
	public int getUserId() {
		return userId;
	}

	/**
	 * Sets the value of the userId property.
	 * 
	 */
	public void setUserId(int value) {
		this.userId = value;
	}

}
