//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.30 at 12:59:51 PM IST 
//


package com.po.reservation.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pslcLocationCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="psProject" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fuzeProjectId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="psProjectStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="psProjectEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="useByDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="psProjectDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="pslcDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pslcLocationCode",
    "psProject",
    "fuzeProjectId",
    "psProjectStatus",
    "psProjectEffectiveDate",
    "useByDate",
    "psProjectDescription",
    "pslcDescription",
    "message",
    "status"
})
@XmlRootElement(name = "ReuseProjectDetailsResponse", namespace = "http://www.fuze.reservation.application.com/reuseprojectdetails")
public class ReuseProjectDetailsResponse {

    @XmlElement(namespace = "http://www.fuze.reservation.application.com/reuseprojectdetails", required = true)
    protected String pslcLocationCode;
    @XmlElement(namespace = "http://www.fuze.reservation.application.com/reuseprojectdetails", required = true)
    protected String psProject;
    @XmlElement(namespace = "http://www.fuze.reservation.application.com/reuseprojectdetails", required = true)
    protected String fuzeProjectId;
    @XmlElement(namespace = "http://www.fuze.reservation.application.com/reuseprojectdetails", required = true)
    protected String psProjectStatus;
    @XmlElement(namespace = "http://www.fuze.reservation.application.com/reuseprojectdetails", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar psProjectEffectiveDate;
    @XmlElement(namespace = "http://www.fuze.reservation.application.com/reuseprojectdetails", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar useByDate;
    @XmlElement(namespace = "http://www.fuze.reservation.application.com/reuseprojectdetails", required = true)
    protected String psProjectDescription;
    @XmlElement(namespace = "http://www.fuze.reservation.application.com/reuseprojectdetails", required = true)
    protected String pslcDescription;
    @XmlElement(namespace = "http://www.fuze.reservation.application.com/reuseprojectdetails", required = true)
    protected String message;
    @XmlElement(namespace = "http://www.fuze.reservation.application.com/reuseprojectdetails", required = true)
    protected Integer status;

    /**
     * Gets the value of the pslcLocationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPslcLocationCode() {
        return pslcLocationCode;
    }

    /**
     * Sets the value of the pslcLocationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPslcLocationCode(String value) {
        this.pslcLocationCode = value;
    }

    /**
     * Gets the value of the psProject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsProject() {
        return psProject;
    }

    /**
     * Sets the value of the psProject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsProject(String value) {
        this.psProject = value;
    }

    /**
     * Gets the value of the fuzeProjectId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuzeProjectId() {
        return fuzeProjectId;
    }

    /**
     * Sets the value of the fuzeProjectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuzeProjectId(String value) {
        this.fuzeProjectId = value;
    }

    /**
     * Gets the value of the psProjectStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsProjectStatus() {
        return psProjectStatus;
    }

    /**
     * Sets the value of the psProjectStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsProjectStatus(String value) {
        this.psProjectStatus = value;
    }

    /**
     * Gets the value of the psProjectEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPsProjectEffectiveDate() {
        return psProjectEffectiveDate;
    }

    /**
     * Sets the value of the psProjectEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPsProjectEffectiveDate(XMLGregorianCalendar value) {
        this.psProjectEffectiveDate = value;
    }

    /**
     * Gets the value of the useByDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUseByDate() {
        return useByDate;
    }

    /**
     * Sets the value of the useByDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUseByDate(XMLGregorianCalendar value) {
        this.useByDate = value;
    }

    /**
     * Gets the value of the psProjectDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsProjectDescription() {
        return psProjectDescription;
    }

    /**
     * Sets the value of the psProjectDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsProjectDescription(String value) {
        this.psProjectDescription = value;
    }

    /**
     * Gets the value of the pslcDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPslcDescription() {
        return pslcDescription;
    }

    /**
     * Sets the value of the pslcDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPslcDescription(String value) {
        this.pslcDescription = value;
    }

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

    
    
    
}
