//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.04 at 05:02:18 PM IST 
//


package com.fuze.po.PurchaseOrderAppServices.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cartId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="itemIds" type="{http://www.poaddcartitemsproducer.com/addcartitems}ItemIdsPojo" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cartId",
    "itemIds"
})
@XmlRootElement(name = "AddCartItemsRequest", namespace = "http://www.poaddcartitemsproducer.com/addcartitems")
public class AddCartItemsRequest {

    @XmlElement(namespace = "http://www.poaddcartitemsproducer.com/addcartitems")
    protected int cartId;
    @XmlElement(namespace = "http://www.poaddcartitemsproducer.com/addcartitems")
    protected List<ItemIdsPojo> itemIds;

    /**
     * Gets the value of the cartId property.
     * 
     */
    public int getCartId() {
        return cartId;
    }

    /**
     * Sets the value of the cartId property.
     * 
     */
    public void setCartId(int value) {
        this.cartId = value;
    }

    /**
     * Gets the value of the itemIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemIdsPojo }
     * 
     * 
     */
    public List<ItemIdsPojo> getItemIds() {
        if (itemIds == null) {
            itemIds = new ArrayList<ItemIdsPojo>();
        }
        return this.itemIds;
    }

}
