//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.26 at 04:31:22 PM IST 
//


package com.fuze.po.PurchaseOrderAppServices.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="poreq" type="{http://www.createpocartproducer.com/createpo}poreq"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "poreq"
})
@XmlRootElement(name = "AddPODetailsRequest")
public class AddPODetailsRequest {

    @XmlElement(required = true)
    protected Poreq poreq;

    /**
     * Gets the value of the poreq property.
     * 
     * @return
     *     possible object is
     *     {@link Poreq }
     *     
     */
    public Poreq getPoreq() {
        return poreq;
    }

    /**
     * Sets the value of the poreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Poreq }
     *     
     */
    public void setPoreq(Poreq value) {
        this.poreq = value;
    }

}
