//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 11:16:20 AM IST 
//


package com.fuze.po.PurchaseOrderAppServices.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fuze.po.PurchaseOrderAppServices.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fuze.po.PurchaseOrderAppServices.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CartDetailsRequest }
     * 
     */
    public CartDetailsRequest createCartDetailsRequest() {
        return new CartDetailsRequest();
    }

    /**
     * Create an instance of {@link CartItemsDetailsResponse }
     * 
     */
    public CartItemsDetailsResponse createCartItemsDetailsResponse() {
        return new CartItemsDetailsResponse();
    }

    /**
     * Create an instance of {@link Cartitems }
     * 
     */
    public Cartitems createCartitems() {
        return new Cartitems();
    }

    /**
     * Create an instance of {@link Cart }
     * 
     */
    public Cart createCart() {
        return new Cart();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link AddPODetailsRequest }
     * 
     */
    public AddPODetailsRequest createAddPODetailsRequest() {
        return new AddPODetailsRequest();
    }

    /**
     * Create an instance of {@link Poreq }
     * 
     */
    public Poreq createPoreq() {
        return new Poreq();
    }

    /**
     * Create an instance of {@link AddPODetailsResponse }
     * 
     */
    public AddPODetailsResponse createAddPODetailsResponse() {
        return new AddPODetailsResponse();
    }

    /**
     * Create an instance of {@link Pores }
     * 
     */
    public Pores createPores() {
        return new Pores();
    }

    /**
     * Create an instance of {@link Itempojo }
     * 
     */
    public Itempojo createItempojo() {
        return new Itempojo();
    }

    /**
     * Create an instance of {@link POListRequest }
     * 
     */
    public POListRequest createPOListRequest() {
        return new POListRequest();
    }

    /**
     * Create an instance of {@link POListResponse }
     * 
     */
    public POListResponse createPOListResponse() {
        return new POListResponse();
    }

    /**
     * Create an instance of {@link Porespojo }
     * 
     */
    public Porespojo createPorespojo() {
        return new Porespojo();
    }

    /**
     * Create an instance of {@link POReqEditRequest }
     * 
     */
    public POReqEditRequest createPOReqEditRequest() {
        return new POReqEditRequest();
    }

    /**
     * Create an instance of {@link POReqEditResponse }
     * 
     */
    public POReqEditResponse createPOReqEditResponse() {
        return new POReqEditResponse();
    }

    /**
     * Create an instance of {@link Poreqeditpojo }
     * 
     */
    public Poreqeditpojo createPoreqeditpojo() {
        return new Poreqeditpojo();
    }

    /**
     * Create an instance of {@link POReqStatusRequest }
     * 
     */
    public POReqStatusRequest createPOReqStatusRequest() {
        return new POReqStatusRequest();
    }

    /**
     * Create an instance of {@link POReqStatusResponse }
     * 
     */
    public POReqStatusResponse createPOReqStatusResponse() {
        return new POReqStatusResponse();
    }
    /**
     * Create an instance of {@link AddCartItemsRequest }
     * 
     */
    public AddCartItemsRequest createAddCartItemsRequest() {
        return new AddCartItemsRequest();
    }

    /**
     * Create an instance of {@link ItemIdsPojo }
     * 
     */
    public ItemIdsPojo createItemIdsPojo() {
        return new ItemIdsPojo();
    }

    /**
     * Create an instance of {@link AddCartItemsResponse }
     * 
     */
    public AddCartItemsResponse createAddCartItemsResponse() {
        return new AddCartItemsResponse();
    }


}
