//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.18 at 10:09:56 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.addcontainerdetails.com/addcontainerdetails", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.addcontainerdetails.addcontainerdetails;
