//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.16 at 02:45:04 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fuze.reservation.application.com/reuseprojectdetails", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.application.reservation.fuze.reuseprojectdetails;
