//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.26 at 06:12:49 PM IST 
//


package com.application.reservation.fuze.reuseprojectdetails;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pslcLocationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="psProject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pslcLocationCode",
    "psProject"
})
@XmlRootElement(name = "ReuseProjectDetailsRequest")
public class ReuseProjectDetailsRequest {

    @XmlElement(required = true)
    protected String pslcLocationCode;
    @XmlElement(required = true)
    protected String psProject;

    /**
     * Gets the value of the pslcLocationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPslcLocationCode() {
        return pslcLocationCode;
    }

    /**
     * Sets the value of the pslcLocationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPslcLocationCode(String value) {
        this.pslcLocationCode = value;
    }

    /**
     * Gets the value of the psProject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsProject() {
        return psProject;
    }

    /**
     * Sets the value of the psProject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsProject(String value) {
        this.psProject = value;
    }

}
