//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.11 at 09:45:23 PM IST 
//


package com.application.reservation.fuze.reuseprojectdetails;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pslcLocationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="psProject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fuzeProjectId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="psProjectStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="psProjectEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="useByDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="psProjectDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pslcDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pslcLocationCode",
    "psProject",
    "fuzeProjectId",
    "psProjectStatus",
    "psProjectEffectiveDate",
    "useByDate",
    "psProjectDescription",
    "pslcDescription",
    "message",
    "status"
})
@XmlRootElement(name = "ReuseProjectDetailsResponse")
public class ReuseProjectDetailsResponse {

    @XmlElement(required = true)
    protected String pslcLocationCode;
    @XmlElement(required = true)
    protected String psProject;
    @XmlElement(required = true)
    protected String fuzeProjectId;
    @XmlElement(required = true)
    protected String psProjectStatus;
    @XmlElement(required = true)
    protected String psProjectEffectiveDate;
    @XmlElement(required = true)
    protected String useByDate;
    @XmlElement(required = true)
    protected String psProjectDescription;
    @XmlElement(required = true)
    protected String pslcDescription;
    @XmlElement(required = true)
    protected String message;
    protected int status;

    /**
     * Gets the value of the pslcLocationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPslcLocationCode() {
        return pslcLocationCode;
    }

    /**
     * Sets the value of the pslcLocationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPslcLocationCode(String value) {
        this.pslcLocationCode = value;
    }

    /**
     * Gets the value of the psProject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsProject() {
        return psProject;
    }

    /**
     * Sets the value of the psProject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsProject(String value) {
        this.psProject = value;
    }

    /**
     * Gets the value of the fuzeProjectId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuzeProjectId() {
        return fuzeProjectId;
    }

    /**
     * Sets the value of the fuzeProjectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuzeProjectId(String value) {
        this.fuzeProjectId = value;
    }

    /**
     * Gets the value of the psProjectStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsProjectStatus() {
        return psProjectStatus;
    }

    /**
     * Sets the value of the psProjectStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsProjectStatus(String value) {
        this.psProjectStatus = value;
    }

    /**
     * Gets the value of the psProjectEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsProjectEffectiveDate() {
        return psProjectEffectiveDate;
    }

    /**
     * Sets the value of the psProjectEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsProjectEffectiveDate(String value) {
        this.psProjectEffectiveDate = value;
    }

    /**
     * Gets the value of the useByDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseByDate() {
        return useByDate;
    }

    /**
     * Sets the value of the useByDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseByDate(String value) {
        this.useByDate = value;
    }

    /**
     * Gets the value of the psProjectDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPsProjectDescription() {
        return psProjectDescription;
    }

    /**
     * Sets the value of the psProjectDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPsProjectDescription(String value) {
        this.psProjectDescription = value;
    }

    /**
     * Gets the value of the pslcDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPslcDescription() {
        return pslcDescription;
    }

    /**
     * Sets the value of the pslcDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPslcDescription(String value) {
        this.pslcDescription = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public int getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(int value) {
        this.status = value;
    }

}
